all:
  jmsPaymentPlugin:
    # You can overwrite these values in your global app.yml
    paypal:
      # PayPal API credentials
      username: ~
      signature: ~
      password: ~
      
      # Whether people need a verified PayPal account for payments
      verified_account_required: false